apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-presenter-api-deployment
  namespace: development
  labels:
    app: team-presenter-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-presenter-api
  template:
    metadata:
      labels:
        app: team-presenter-api
    spec:
      containers:
        - name: team-presenter-api
          image: gcavalli97/chaos-engineering-team-presenter-ms
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
