apiVersion: v1
kind: Service
metadata:
  name: team-presenter-api-service
  namespace: development
spec:
  selector:
    app: team-presenter-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
